const products=[
{id:1,name:'Whey Protein',cat:'proteina',price:35000,b:'DESTACADO',d:'Producto de nutrición deportiva presentado en formato demo.',img:'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?auto=format&fit=crop&w=900&q=85'},
{id:2,name:'Proteína Chocolate',cat:'proteina',price:33000,b:'POPULAR',d:'Opción con sabor chocolate para el catálogo.',img:'https://images.unsplash.com/photo-1622484211148-5c6a5b3f4e2c?auto=format&fit=crop&w=900&q=85'},
{id:3,name:'Pre-Workout',cat:'energia',price:28000,b:'ENERGÍA',d:'Producto deportivo presentado como artículo de catálogo.',img:'https://images.unsplash.com/photo-1590402494682-cd3fb53b1f70?auto=format&fit=crop&w=900&q=85'},
{id:4,name:'Electrolitos',cat:'energia',price:18000,b:'SPORT',d:'Producto de hidratación deportiva para la tienda demo.',img:'https://images.unsplash.com/photo-1546484959-fce7b5b5a5e1?auto=format&fit=crop&w=900&q=85'},
{id:5,name:'Multivitamínico',cat:'bienestar',price:22000,b:'BIENESTAR',d:'Complemento nutricional mostrado como ejemplo.',img:'https://images.unsplash.com/photo-1550572017-4812f4a6c9f8?auto=format&fit=crop&w=900&q=85'},
{id:6,name:'Minerales',cat:'bienestar',price:19000,b:'NUEVO',d:'Producto de bienestar para ampliar el catálogo.',img:'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?auto=format&fit=crop&w=900&q=85'},
{id:7,name:'Shaker Forge',cat:'accesorios',price:9000,b:'ACCESORIO',d:'Shaker reutilizable para complementar la tienda.',img:'https://images.unsplash.com/photo-1594737625785-c9f5e5d0b8e5?auto=format&fit=crop&w=900&q=85'},
{id:8,name:'Botella Sport',cat:'accesorios',price:12000,b:'NUEVO',d:'Botella deportiva para completar el catálogo.',img:'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=900&q=85'}];
let cart=JSON.parse(localStorage.getItem('forgeCart')||'[]');
const grid=document.getElementById('grid'),items=document.getElementById('items'),empty=document.getElementById('empty'),count=document.getElementById('count'),sub=document.getElementById('subtotal'),tot=document.getElementById('total');
const names={proteina:'Proteínas',energia:'Energía',bienestar:'Bienestar',accesorios:'Accesorios'};
const money=n=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(n);
function render(filter='todos'){let a=filter==='todos'?products:products.filter(x=>x.cat===filter);grid.innerHTML=a.map(x=>`<article class="product"><div class="pic"><img src="${x.img}" alt="${x.name}" onerror="this.style.display='none'"></div><div class="product-info"><small>${names[x.cat]} · ${x.b}</small><h3>${x.name}</h3><p>${x.d}</p><div class="product-bottom"><span class="price">${money(x.price)}</span><button class="add" data-add="${x.id}">+ AGREGAR</button></div></div></article>`).join('')}
function save(){localStorage.setItem('forgeCart',JSON.stringify(cart))}
function total(){return cart.reduce((s,x)=>s+x.price*x.qty,0)}
function renderCart(){count.textContent=cart.reduce((s,x)=>s+x.qty,0);sub.textContent=money(total());tot.textContent=money(total());empty.style.display=cart.length?'none':'block';items.innerHTML=cart.map(x=>`<div class="cart-item"><img src="${x.img}" alt=""><div><h4>${x.name}</h4><p>${money(x.price)} c/u</p><div class="qty"><button data-m="${x.id}">−</button><b>${x.qty}</b><button data-p="${x.id}">+</button><button class="remove" data-r="${x.id}">ELIMINAR</button></div></div><strong>${money(x.price*x.qty)}</strong></div>`).join('')}
function toast(t){const e=document.getElementById('toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2000)}
function open(id){document.getElementById(id).classList.add('open');document.body.style.overflow='hidden'}function close(id){document.getElementById(id).classList.remove('open');if(!document.querySelector('.modal.open'))document.body.style.overflow=''}
grid.onclick=e=>{let b=e.target.closest('[data-add]');if(!b)return;let p=products.find(x=>x.id==b.dataset.add),i=cart.find(x=>x.id==p.id);i?i.qty++:cart.push({...p,qty:1});save();renderCart();toast(p.name+' agregado al carrito')};
items.onclick=e=>{let id=Number((e.target.closest('[data-p],[data-m],[data-r]')||{}).dataset?.p||(e.target.closest('[data-p],[data-m],[data-r]')||{}).dataset?.m||(e.target.closest('[data-p],[data-m],[data-r]')||{}).dataset?.r);let b=e.target.closest('[data-p],[data-m],[data-r]');if(!b)return;let i=cart.find(x=>x.id==id);if(b.dataset.p)i.qty++;if(b.dataset.m)i.qty--;if(b.dataset.r)i.qty=0;cart=cart.filter(x=>x.qty>0);save();renderCart()};
document.getElementById('filters').onclick=e=>{let b=e.target.closest('[data-filter]');if(!b)return;document.querySelectorAll('.filter').forEach(()=>{});document.querySelectorAll('#filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.filter)};
document.querySelectorAll('.cats button').forEach(b=>b.onclick=()=>{let f=document.querySelector(`[data-filter="${b.dataset.cat}"]`);document.querySelectorAll('#filters button').forEach(x=>x.classList.remove('active'));f.classList.add('active');render(b.dataset.cat);document.getElementById('productos').scrollIntoView({behavior:'smooth'})});
document.getElementById('openCart').onclick=()=>open('cartModal');document.getElementById('closeCart').onclick=()=>close('cartModal');document.getElementById('cartBack').onclick=()=>close('cartModal');document.getElementById('continue').onclick=()=>close('cartModal');document.getElementById('contactButton')?.addEventListener('click',()=>open('cartModal'));
document.getElementById('checkout').onclick=()=>{if(!cart.length)return toast('Agregá algún producto primero');document.getElementById('preview').innerHTML=cart.map(x=>`<p><span>${x.name} × ${x.qty}</span><b>${money(x.price*x.qty)}</b></p>`).join('')+`<p class="p-total"><strong>TOTAL</strong><b>${money(total())}</b></p>`;close('cartModal');open('checkoutModal')};
document.getElementById('closeCheckout').onclick=()=>close('checkoutModal');document.getElementById('checkoutBack').onclick=()=>close('checkoutModal');
document.getElementById('form').onsubmit=e=>{e.preventDefault();alert('PEDIDO SIMULADO\n\nCliente: '+document.getElementById('name').value+'\nEntrega: '+document.getElementById('delivery').value+'\nTotal: '+money(total())+'\n\nNo se realizó ningún pago.');cart=[];save();renderCart();e.target.reset();close('checkoutModal');toast('Pedido simulado confirmado ✓')};
document.getElementById('menuBtn').onclick=()=>document.getElementById('nav').classList.toggle('open');document.addEventListener('keydown',e=>{if(e.key==='Escape'){close('cartModal');close('checkoutModal')}});render();renderCart();